# Generated by Django 4.2.2 on 2023-06-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('neighborhood', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
