# Generated by Django 4.2.2 on 2023-07-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('birth', models.DateTimeField(null=True)),
                ('birthplace', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=200, null=True)),
                ('service', models.CharField(choices=[('Pasteur', 'Pasteur'), ('Théologien', 'Théologien'), ('Diacre', 'Diacre'), ('Evangeliste', 'Evangeliste'), ('Catéchiste', 'Catéchiste'), ('Berger', 'Berger')], max_length=200, null=True)),
                ('works_at', models.CharField(max_length=200, null=True)),
                ('debuted_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
