# Generated by Django 4.2.2 on 2023-06-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Churchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(max_length=200, null=True)),
                ('church_branch', models.CharField(max_length=200, null=True)),
                ('church_tree', models.CharField(max_length=200, null=True)),
                ('church_synod', models.CharField(max_length=200, null=True)),
                ('located_at', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
