# Generated by Django 4.2.2 on 2023-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchs',
            name='church_synod',
            field=models.CharField(choices=[('SPA - Antsiranana', 'SPA - Antsiranana'), (' SPAVA - Sambava', ' SPAVA - Sambava'), ('SPSofia - Antsohihy', 'SPSofia - Antsohihy'), ('SPBM - Mahajanga', 'SPBM - Mahajanga'), ('SPAI - Ambatondrazaka', 'SPAI - Ambatondrazaka'), ('SPTM - Toamasina', 'SPTM - Toamasina'), ('SPAnta - Antananarivo', 'SPAnta - Antananarivo'), ('SPN - Marolambo', 'SPN - Marolambo'), ('SPAN - Mananjary', 'SPAN - Mananjary'), ('SPMa - Manakara', 'SPMa - Manakara'), ('SPAts - Farafangana', 'SPAts - Farafangana'), ('SPAV - Vondrozo', 'SPAV - Vondrozo'), ('SPFa - Faradofay', 'SPFa - Faradofay'), ('SPAA - Ambovombe Androy', 'SPAA - Ambovombe Androy'), ('SPAB - Betroka', 'SPAB - Betroka'), ('SPH - Ihosy', 'SPH - Ihosy'), ('SPBA - Betioky Atsimo', 'SPBA - Betioky Atsimo'), ('SPFT - Toliara', 'SPFT - Toliara'), ('SPAf - Fianarantsoa', 'SPAf - Fianarantsoa'), ('SPATsim - Ambatofinandrahana', 'SPATsim - Ambatofinandrahana'), ('SPM - Morondava', 'SPM - Morondava'), ('SPAFI - Fandriana', 'SPAFI - Fandriana'), ('SPAM - Antsirabe', 'SPAM - Antsirabe'), ('SPMel - Maintirano', 'SPMel - Maintirano'), ('FLME - Europa', 'FLME - Europa')], max_length=200, null=True),
        ),
    ]
