# Generated by Django 4.2.2 on 2023-07-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sacraments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('birth', models.DateTimeField(null=True)),
                ('birthplace', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=200, null=True)),
                ('sacrament_date', models.DateTimeField(null=True)),
                ('father', models.CharField(max_length=200, null=True)),
                ('mother', models.CharField(max_length=200, null=True)),
                ('familytree', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('neighborhood', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
