# Generated by Django 4.2.2 on 2023-07-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('birth', models.DateTimeField(null=True)),
                ('birthplace', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=200, null=True)),
                ('job', models.CharField(max_length=200, null=True)),
                ('diploma', models.CharField(max_length=200, null=True)),
                ('baptism', models.DateTimeField(null=True)),
                ('sacrament', models.DateTimeField(null=True)),
                ('faction', models.CharField(max_length=200, null=True)),
                ('situation', models.CharField(blank=True, choices=[('Marié(e)', 'Marié(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Célibataire', 'Célibataire')], default='Célibataire', max_length=200, null=True)),
                ('engagement', models.DateTimeField(null=True)),
                ('marriage', models.DateTimeField(null=True)),
                ('familytree', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
