# Generated by Django 4.2.2 on 2023-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('surname', models.CharField(max_length=200, null=True)),
                ('birth', models.DateTimeField(auto_now_add=True, null=True)),
                ('birthplace', models.CharField(max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=200, null=True)),
                ('job', models.CharField(max_length=200, null=True)),
                ('diploma', models.CharField(max_length=200, null=True)),
                ('baptism', models.DateTimeField(auto_now_add=True, null=True)),
                ('sacrament', models.DateTimeField(auto_now_add=True, null=True)),
                ('faction', models.CharField(max_length=200, null=True)),
                ('situation', models.CharField(blank=True, choices=[('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Célibataire', 'Célibataire')], max_length=200, null=True)),
                ('engagement', models.DateTimeField(auto_now_add=True, null=True)),
                ('marriage', models.DateTimeField(auto_now_add=True, null=True)),
                ('familytree', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
