# Generated by Django 4.2.2 on 2023-06-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_sex_alter_members_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='sex',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default=' ', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='situation',
            field=models.CharField(blank=True, choices=[('Marié', 'Marié'), ('Divorcé', 'Divorcé'), ('Célibataire', 'Célibataire')], default=' ', max_length=200, null=True),
        ),
    ]
