# Generated by Django 4.2.2 on 2023-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_members_sex_alter_members_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='situation',
            field=models.CharField(blank=True, choices=[('Marié(e)', 'Marié(e)'), ('Veuf(ve)', 'Veuf(ve)'), ('Célibataire', 'Célibataire')], default='Célibataire', max_length=200, null=True),
        ),
    ]
